version: "3"

services:
  socket:
    container_name: chat-socket
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - GW_ENDPOINT=0.0.0.0:3001
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AWS_REGION=${AWS_REGION}
      
    volumes:
      - ./:/home/app:rw
