service: visor-chat-lmb-socket
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ${env:AWS_REGION}
  environment:
    GW_ENDPOINT: ${env:GW_ENDPOINT}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    AWS_COGNITO_REGION: ${env:AWS_REGION}

functions:
  ChatLmbSocket:
    handler: index.handler

    # events:
    #   - websocket:
    #       route: $connect
    #   - websocket:
    #       route: $disconnect
    #   - websocket:
    #       route: $default
    #   - websocket:
    #       route: sendMessage
plugins:
  - serverless-offline

custom:
  # This is necessary because the docker to use this host
  serverless-offline:
    host: 0.0.0.0
