service: visor-chat-lmb-socket
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ${env:AWS_REGION}

  # This is necessary to use only api to multi-resource
  apiGateway:
    restApiId: ${env:AWS_API_GATEWAY_ID}
    restApiRootResourceId: ${env:AWS_API_GATEWAY_RESOURCE_ID}

functions:
  functionName:
    ChatLmb:
    # Environment variables need to be in OS
    environment:
      AWS_REGION: ${env:AWS_REGION}
    handler: index.handler
    events:
      # Accept any path that is added to the service
      - http:
          path: /chat/{proxy+}
          method: ANY

# Hide endpoint in the output deploy
noDeploy: true

plugins:
  # plus to serverless work offile
  - serverless-offline

custom:
  # This is necessary because the docker to use this host
  serverless-offline:
    host: 0.0.0.0
