name: Pipeline Workflow

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"

  pull_request:
    types: [opened, synchronize]
    branches: ["main"]
    paths-ignore:
      - "README.md"

jobs:
  build:
    name: Build
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.state == 'open') }}
    uses: ./.github/workflows/build.yml
    with:
      node-version: "18"

  release:
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    uses: ./.github/workflows/release.yml
    needs: build
    with:
      node-version: "18"
    secrets:
      GW_ENDPOINT: ${{ vars.GW_ENDPOINT }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION}}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}