name: Pipeline Workflow

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"

  pull_request:
    types: [opened, synchronize]
    branches: ["main"]
    paths-ignore:
      - "README.md"

jobs:
  build:
    name: Build
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.state == 'open') }}
    uses: ./.github/workflows/build.yml
    with:
      node-version: "18"

  # release:
  #   if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
  #   uses: ./.github/workflows/release.yml
  #   needs: build
  #   with:
  #     node-version: "18"
  #   secrets:
  #     AWS_COGNITO_REGION: ${{ vars.AWS_COGNITO_REGION }}
  #     AWS_COGNITO_CLIENT_ID: ${{ secrets.AWS_COGNITO_CLIENT_ID }}
  #     AWS_API_GATEWAY_ID: ${{ secrets.AWS_API_GATEWAY_ID}}
  #     AWS_API_GATEWAY_RESOURCE_ID: ${{ secrets.AWS_API_GATEWAY_RESOURCE_ID }}
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
